# Generated by Django 5.0.2 on 2024-02-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author_ip',
        ),
    ]
